-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 19, 2019 at 05:59 PM
-- Server version: 10.1.38-MariaDB
-- PHP Version: 7.3.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `hotels`
--

-- --------------------------------------------------------

--
-- Table structure for table `gallery`
--

CREATE TABLE `gallery` (
  `id` int(11) NOT NULL,
  `hotel_id` varchar(1000) NOT NULL,
  `profile_picture_path` mediumtext NOT NULL,
  `cover_photo_path` mediumtext NOT NULL,
  `slider_image_path` varchar(1000) NOT NULL,
  `gallery_image_path` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `gallery`
--

INSERT INTO `gallery` (`id`, `hotel_id`, `profile_picture_path`, `cover_photo_path`, `slider_image_path`, `gallery_image_path`) VALUES
(5, '58', '../../Gallery_Images/58/Profile_Picture/profile.jpg', '../../Gallery_Images/58/Cover_Photo/cover.jpg', '../Gallery_Images_XML/58/Slider/Data.json', '../Gallery_Images_XML/58/Gallery/Data.json'),
(6, '233', '../../Gallery_Images/233/Profile_Picture/profile.jpg', '../../Gallery_Images/233/Cover_Photo/cover.jpg', '../Gallery_Images_XML/233/Slider/Data.json', '../Gallery_Images_XML/233/Gallery/Data.json'),
(7, '232', '../../Gallery_Images/232/Profile_Picture/profile.jpg', '../../Gallery_Images/232/Cover_Photo/cover.jpg', '../Gallery_Images_XML/232/Slider/Data.json', '../Gallery_Images_XML/232/Gallery/Data.json');

-- --------------------------------------------------------

--
-- Table structure for table `hotel_details`
--

CREATE TABLE `hotel_details` (
  `id` int(11) NOT NULL,
  `hotel_name` varchar(100) NOT NULL,
  `address` varchar(300) NOT NULL,
  `district` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `phone` varchar(12) NOT NULL,
  `website` varchar(150) NOT NULL,
  `lat` float NOT NULL,
  `lng` float NOT NULL,
  `gallery` varchar(10) NOT NULL,
  `description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `hotel_details`
--

INSERT INTO `hotel_details` (`id`, `hotel_name`, `address`, `district`, `email`, `phone`, `website`, `lat`, `lng`, `gallery`, `description`) VALUES
(65, 'Jetwing Vil Uyana', 'Sigiriya, 21120', 'Nuwara Eliya', 'Uyana@ymail.com', '000', 'Uyana.lk', 7.93086, 80.7208, 'false', '7'),
(66, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', '1'),
(67, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', '2'),
(68, 'Signature by Amaya', 'Sigiriya, Dambulla 21100', 'Badulla', 'Signature@outlook.com', '66446500', 'Amaya.com', 7.89156, 80.6996, 'false', '3'),
(69, 'Surfing Wombats Hostel', 'Midigama A2, Ahangama 80860', 'Colombo', 'Surfing@gmail.com', '412254766', 'Surfing.lk', 5.96648, 80.3918, 'false', '4'),
(71, 'Ulagalla by Uga Escapes', 'Ulagalla Walawwa, Thirippane Ulagalla Road  50072 LK', 'Batticaloa', 'Ulagalla@gamil.com', '112328832', 'Ulagalla.com', 8.2061, 80.545, 'false', '6'),
(72, 'Jetwing Vil Uyana', 'Sigiriya, 21120', 'Kilinochchi', 'Uyana@ymail.com', '662286000', 'Uyana.lk', 7.93086, 80.7208, 'false', '7'),
(74, 'Fresco Water Villa', 'Fresco Water Villa Pvt Ltd, 72/A 4TH Mile Post, Sigiriya', 'Galle', 'Fresco@yahoo.com', '662286161', 'Fresco.com', 7.94573, 80.7355, 'false', '9'),
(75, 'Aliya Resort &amp; Spa', 'Audangawa, Sigiriya 21120', 'Polonnaruwa', 'Aliya@gamil.com', '662040400', 'Aliya.lk', 7.99939, 80.7362, 'false', '10'),
(76, 'Heritance Kandalama', '11, Dambulla 21100', 'Ratnapura', 'Heritance@yahoo.com', '665555000', 'Heritance.com', 7.86953, 80.7068, 'false', '11'),
(77, 'Amaya Lake', 'Kap Ela, Kandalama, Dambulla 21100', 'Puttalam', 'Amaya@yahoo.com', '114767846', 'Amaya.lk', 7.89377, 80.7006, 'false', '12'),
(78, 'Habarana Village by Cinnamon', 'Habarana', 'Colombo', 'Habarana@gamil.com', '662270047', 'Habarana.com', 8.03681, 80.7499, 'false', '13'),
(79, 'Cassandra Culture Resort', 'Sigiriya, Avudangawa', 'Ratnapura', 'Cassandra@yahoo.com', '664933636', 'Cassandra.com', 7.99229, 80.7339, 'false', '14'),
(80, 'Sigiriya Village Hotel', 'Hotel Rd, Sigiriya', 'Matale', 'Sigiriya@yahoo.com', '662286803', 'Sigiriya.lk', 7.9498, 80.7612, 'false', '15'),
(81, 'Sundaras Resort &amp; Spa', '189 Kandy Rd, Dambulla 21100', 'Nuwara Eliya', 'Sundaras@yahoo.com', '727086000', 'Sundaras.lk', 7.84977, 80.6532, 'false', '16'),
(82, 'The Paradise Resort &amp; Spa', 'Kubukkadanwala, Dambulla 21100', 'Mullaitivu', 'Paradise@yahoo.com', '662286300', 'Paradise.lk', 7.89234, 80.7252, 'false', '17'),
(83, 'The Elephant Corridor', 'Pothana,Sigiriya, Kimbissa', 'Puttalam', 'Elephant@gmail.com', '662286950', 'Elephant.lk', 7.94375, 80.7108, 'false', '18'),
(84, 'Camellia Resort and Spa', 'Audangawa, Kibissa, Sigiriya 21120', 'Kegalle', 'Camellia@yahoo.com', '662054103', 'Camellia.com', 7.99528, 80.737, 'false', '19'),
(85, 'Hotel Eden Garden', 'Hotel Eden Garden, Inamaluwa - Sigiriya Rd, Inamaluwa', 'Mannar', 'Garden@yahoo.com', '756800519', 'Garden.com', 7.9299, 80.6887, 'false', '20'),
(86, 'Saunter paradise hotel', 'Ambepussa - Kurunegala - Trincomalee Hwy, Dambulla', 'Batticaloa', 'Saunter@gmail.com', '756865602', 'Saunter.com', 7.99284, 80.7253, 'false', '21'),
(87, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', '1'),
(88, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', '2'),
(89, 'Signature by Amaya', 'Sigiriya, Dambulla 21100', 'Badulla', 'Signature@outlook.com', '66446500', 'Amaya.com', 7.89156, 80.6996, 'false', '3'),
(90, 'Surfing Wombats Hostel', 'Midigama A2, Ahangama 80860', 'Colombo', 'Surfing@gmail.com', '412254766', 'Surfing.lk', 5.96648, 80.3918, 'false', '4'),
(91, 'Ocean Bay Surf Resort', 'A2, Weligama 81700', 'Gampaha', 'Ocean@yahoo.com', '776206233', 'Ocean.com', 5.97461, 80.4383, 'false', '5'),
(92, 'Ulagalla by Uga Escapes', 'Ulagalla Walawwa, Thirippane Ulagalla Road  50072 LK', 'Batticaloa', 'Ulagalla@gamil.com', '112328832', 'Ulagalla.com', 8.2061, 80.545, 'false', '6'),
(93, 'Jetwing Vil Uyana', 'Sigiriya, 21120', 'Kilinochchi', 'Uyana@ymail.com', '662286000', 'Uyana.lk', 7.93086, 80.7208, 'false', '7'),
(94, 'Sigiriana Resort by Thilanka', '51 Godawalaya Morragollawa, Dambulla 21100', 'Kurunegala', 'Thilanka@yahoo.com', '664468001', 'Thilanka.lk', 7.82193, 80.6574, 'false', '8'),
(95, 'Fresco Water Villa', 'Fresco Water Villa Pvt Ltd, 72/A 4TH Mile Post, Sigiriya', 'Galle', 'Fresco@yahoo.com', '662286161', 'Fresco.com', 7.94573, 80.7355, 'false', '9'),
(96, 'Aliya Resort &amp; Spa', 'Audangawa, Sigiriya 21120', 'Polonnaruwa', 'Aliya@gamil.com', '662040400', 'Aliya.lk', 7.99939, 80.7362, 'false', '10'),
(97, 'Heritance Kandalama', '11, Dambulla 21100', 'Ratnapura', 'Heritance@yahoo.com', '665555000', 'Heritance.com', 7.86953, 80.7068, 'false', '11'),
(98, 'Amaya Lake', 'Kap Ela, Kandalama, Dambulla 21100', 'Puttalam', 'Amaya@yahoo.com', '114767846', 'Amaya.lk', 7.89377, 80.7006, 'false', '12'),
(99, 'Habarana Village by Cinnamon', 'Habarana', 'Colombo', 'Habarana@gamil.com', '662270047', 'Habarana.com', 8.03681, 80.7499, 'false', '13'),
(100, 'Cassandra Culture Resort', 'Sigiriya, Avudangawa', 'Ratnapura', 'Cassandra@yahoo.com', '664933636', 'Cassandra.com', 7.99229, 80.7339, 'false', '14'),
(101, 'Sigiriya Village Hotel', 'Hotel Rd, Sigiriya', 'Matale', 'Sigiriya@yahoo.com', '662286803', 'Sigiriya.lk', 7.9498, 80.7612, 'false', '15'),
(102, 'Sundaras Resort &amp; Spa', '189 Kandy Rd, Dambulla 21100', 'Nuwara Eliya', 'Sundaras@yahoo.com', '727086000', 'Sundaras.lk', 7.84977, 80.6532, 'false', '16'),
(103, 'The Paradise Resort &amp; Spa', 'Kubukkadanwala, Dambulla 21100', 'Mullaitivu', 'Paradise@yahoo.com', '662286300', 'Paradise.lk', 7.89234, 80.7252, 'false', '17'),
(104, 'The Elephant Corridor', 'Pothana,Sigiriya, Kimbissa', 'Puttalam', 'Elephant@gmail.com', '662286950', 'Elephant.lk', 7.94375, 80.7108, 'false', '18'),
(105, 'Camellia Resort and Spa', 'Audangawa, Kibissa, Sigiriya 21120', 'Kegalle', 'Camellia@yahoo.com', '662054103', 'Camellia.com', 7.99528, 80.737, 'false', '19'),
(106, 'Hotel Eden Garden', 'Hotel Eden Garden, Inamaluwa - Sigiriya Rd, Inamaluwa', 'Mannar', 'Garden@yahoo.com', '756800519', 'Garden.com', 7.9299, 80.6887, 'false', '20'),
(107, 'Saunter paradise hotel', 'Ambepussa - Kurunegala - Trincomalee Hwy, Dambulla', 'Batticaloa', 'Saunter@gmail.com', '756865602', 'Saunter.com', 7.99284, 80.7253, 'false', '21'),
(108, 'Amaya Signature', 'Sun Shine Villa, Thalkotta Rd, Dambulla 21120', 'Batticaloa', 'Amaya@yahoo.com', '65665644', 'Amaya.lk', 7.89133, 80.6994, 'false', '22'),
(109, 'Amaara Forest Hotel', 'Indigaswewa, Sigiriya, Dambulla', 'Colombo', 'Amaara@yahoo.com', '56568855', 'Amaara.com', 8.00136, 80.7475, 'false', '23'),
(110, 'Grand Kalundawa Waterfront Resort', 'Dambulla, Kalundawa Road, Dambuluoya Junction,', 'Colombo', 'Grand@yahoo.com', '727086000', 'Kalundawa .com', 7.80659, 80.659, 'false', '24'),
(111, 'RHO Sigiriya Lake Edge Retreat', '143/B/3, Egodawewa Road, Galahitiyawa, Sigiriya', 'Puttalam', 'Sigiriya@yahoo.com', '56565656', 'Sigiriya.com', 7.93229, 80.7447, 'false', '25'),
(112, 'Wild Grass Nature Resort', 'Kumbukkadanwala Farmhouse Road Govigammanaya Main Road Kumbukkadanwala Sigiriya, Dambulla', 'Ratnapura', 'Wild@yahoo.com', '65656569', 'Wild.com', 7.90508, 80.7245, 'false', '26'),
(113, 'Pelwehera Village Resort', 'Bulagala Junction, Habarana Road, Dambulla 21120', 'Nuwara Eliya', 'Pelwehera@yhoo.com', '56566656565', 'Pelwehera.com', 7.90391, 80.6694, 'false', '27'),
(114, 'Hotel Sigiriya', 'Hotel Road, Sigiriya, Sigiriya', 'Mannar', 'Sigiriya@yahoo.com', '56565646', 'Sigiriya.lk', 7.95044, 80.7631, 'false', '28'),
(115, 'EKHO Sigiriya', 'Hotel Road, Sigiriya, Sigiriya', 'Colombo', 'EKHO@gmail.com', '65684462', 'EKHO.lk', 7.95209, 80.7552, 'false', '29'),
(116, 'Gimanhala Hotel', 'Jaffna - Kandy Highway, 754 Anuradhapura Road, DambullaJaffna', 'Jaffna', 'Gimanhala@yahoo.com', '662286300', 'Gimanhala.com', 7.88025, 80.6507, 'false', '30'),
(117, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', '1'),
(118, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', '2'),
(119, 'Signature by Amaya', 'Sigiriya, Dambulla 21100', 'Badulla', 'Signature@outlook.com', '66446500', 'Amaya.com', 7.89156, 80.6996, 'false', '3'),
(120, 'Surfing Wombats Hostel', 'Midigama A2, Ahangama 80860', 'Colombo', 'Surfing@gmail.com', '412254766', 'Surfing.lk', 5.96648, 80.3918, 'false', '4'),
(121, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', '1'),
(122, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', '2'),
(123, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', ''),
(124, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', ''),
(125, 'Signature by Amaya', 'Sigiriya, Dambulla 21100', 'Badulla', 'Signature@outlook.com', '66446500', 'Amaya.com', 7.89156, 80.6996, 'false', ''),
(126, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', ''),
(127, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', ''),
(128, 'sajdklasj', 'jkljkldjaslk', 'Ampara', 'dk@gmail.com', '54545', 'dksadlas', 65656, 5656, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16'),
(129, 'sajdklasj', 'jkljkldjaslk', 'Ampara', 'dk@gmail.com', '54545', 'dksadlas', 65656, 5656, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sigiriya, an ancient city and fortress.The polished, warmly decorated rooms feature cable TV, free Wi-Fi and minifridges, along with tea and coffeemaking facilities. Upgraded rooms add butler service and verandas. Chic 2-bedroom suites include dining areas and whirlpool baths.The hotel has a bar, a teahouse and 2 restaurants, which offer organic dishes and open-air dining. Other amenities include a spa, tennis'),
(130, 'sajdklasj', 'jkljkldjaslk', 'Ampara', 'dk@gmail.com', '54545', 'dksadlas', 65656, 5656, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sigiriya, an ancient city and fortress.The polished, warmly decorated rooms feature cable TV, free Wi-Fi and minifridges, along with tea and coffeemaking facilities. Upgraded rooms add butler service and verandas. Chic 2-bedroom suites include dining areas and whirlpool baths.The hotel has a bar, a teahouse and 2 restaurants, which offer organic dishes and open-air dining.'),
(131, 'sajdklasj', 'jkljkldjaslk', 'Ampara', 'dk@gmail.com', '54545', 'dksadlas', 65656, 5656, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sigiriya, an ancient city and fortress.The polished, warmly decorated rooms feature cable TV, free Wi-Fi and minifridges, along with tea and coffeemaking facilities. Upgraded rooms add butler service and verandas. Chic 2-bedroom suites include dining areas and whirlpool baths.The hotel has a bar, a teahouse and 2 restaurants, which offer organic dishes and open-air dining.'),
(132, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sigiriya, an ancient city and fortress.The polished, warmly decorated rooms feature cable TV, free Wi-Fi and minifridges, along with tea and coffeemaking facilities. Upgraded rooms add butler service and verandas. Chic 2-bedroom suites include dining areas and whirlpool baths.The hotel has a bar, a teahouse and 2 restaurants, which offer organic dishes and open-air dining.'),
(133, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.'),
(134, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sigiriya, an ancient city and fortress.The polished, warmly decorated rooms feature cable TV, free Wi-Fi and minifridges, along with tea and coffeemaking facilities. Upgraded rooms add butler service and verandas. Chic 2-bedroom suites include dining areas and whirlpool baths.The hotel has a bar, a tea'),
(135, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living a'),
(136, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sig'),
(137, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from'),
(138, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sig'),
(139, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from'),
(140, 'Signature by Amaya', 'Sigiriya, Dambulla 21100', 'Badulla', 'Signature@outlook.com', '66446500', 'Amaya.com', 7.89156, 80.6996, 'false', 'Room service is available.Theres a colourful rooftop terrace with a pool and a bar serving light bit'),
(141, 'Surfing Wombats Hostel', 'Midigama A2, Ahangama 80860', 'Colombo', 'Surfing@gmail.com', '412254766', 'Surfing.lk', 5.96648, 80.3918, 'false', 'Chic hostel offering airy dorms &amp; private rooms, plus outdoor showers &amp; a restaurant.'),
(142, 'Ocean Bay Surf Resort', 'A2, Weligama 81700', 'Gampaha', 'Ocean@yahoo.com', '776206233', 'Ocean.com', 5.97461, 80.4383, 'false', 'Peaceful place with friendly staff. Lovely place for couples for weekend getaway. Payments will not'),
(143, 'Ulagalla by Uga Escapes', 'Ulagalla Walawwa, Thirippane Ulagalla Road  50072 LK', 'Batticaloa', 'Ulagalla@gamil.com', '112328832', 'Ulagalla.com', 8.2061, 80.545, 'false', 'On the site of a 19th-century estate, this high-end resort is 3 km from the A9 highway, and 28 km fr'),
(144, 'Jetwing Vil Uyana', 'Sigiriya, 21120', 'Kilinochchi', 'Uyana@ymail.com', '662286000', 'Uyana.lk', 7.93086, 80.7208, 'false', 'On sprawling grounds with reed beds, paddy fields and a lake, this imaginative, eco-chic hotel is 15'),
(145, 'Sigiriana Resort by Thilanka', '51 Godawalaya Morragollawa, Dambulla 21100', 'Kurunegala', 'Thilanka@yahoo.com', '664468001', 'Thilanka.lk', 7.82193, 80.6574, 'false', 'Surrounded by woodland, this unfussy hotel is an 8-minute walk from Dambulla river and 4 km from the'),
(146, 'Fresco Water Villa', 'Fresco Water Villa Pvt Ltd, 72/A 4TH Mile Post, Sigiriya', 'Galle', 'Fresco@yahoo.com', '662286161', 'Fresco.com', 7.94573, 80.7355, 'false', 'Amid lush, sprawling gardens, this upscale hotel is 3 km from the ancient Sigiriya Lion Rock fortres'),
(147, 'Aliya Resort &amp; Spa', 'Audangawa, Sigiriya 21120', 'Polonnaruwa', 'Aliya@gamil.com', '662040400', 'Aliya.lk', 7.99939, 80.7362, 'false', 'Set across a streamlined complex in the lush countryside, this refined resort is less than 1 km from'),
(148, 'Heritance Kandalama', '11, Dambulla 21100', 'Ratnapura', 'Heritance@yahoo.com', '665555000', 'Heritance.com', 7.86953, 80.7068, 'false', 'Set amidst jungle on a mountainside overlooking the Sigiriya rock fortress, this eco-chic hotel is n'),
(149, 'Amaya Lake', 'Kap Ela, Kandalama, Dambulla 21100', 'Puttalam', 'Amaya@yahoo.com', '114767846', 'Amaya.lk', 7.89377, 80.7006, 'false', 'A nice hotel surrounded by greenery and by the Kandalama lake. Very salubrious and you can see many'),
(150, 'Habarana Village by Cinnamon', 'Habarana', 'Colombo', 'Habarana@gamil.com', '662270047', 'Habarana.com', 8.03681, 80.7499, 'false', 'Set amid lush forest off the A6 highway, this relaxed, rural resort on Habarana Lake is 18 km from S'),
(151, 'Cassandra Culture Resort', 'Sigiriya, Avudangawa', 'Ratnapura', 'Cassandra@yahoo.com', '664933636', 'Cassandra.com', 7.99229, 80.7339, 'false', 'Wonderful hotel, the buffet is delicious and offers plenty of choice. Beautiful pool. The staff is s'),
(152, 'Sigiriya Village Hotel', 'Hotel Rd, Sigiriya', 'Matale', 'Sigiriya@yahoo.com', '662286803', 'Sigiriya.lk', 7.9498, 80.7612, 'false', 'On 10 landscaped hectares, this scenic resort is less than 1 km from the ruined rock fortress at Sig'),
(153, 'Sundaras Resort &amp; Spa', '189 Kandy Rd, Dambulla 21100', 'Nuwara Eliya', 'Sundaras@yahoo.com', '727086000', 'Sundaras.lk', 7.84977, 80.6532, 'false', 'On wooded grounds off the Kandyâ€“Jaffna Highway, this relaxed hotel is 1 km from the Golden Temple of'),
(154, 'The Paradise Resort &amp; Spa', 'Kubukkadanwala, Dambulla 21100', 'Mullaitivu', 'Paradise@yahoo.com', '662286300', 'Paradise.lk', 7.89234, 80.7252, 'false', 'This relaxed resort is 3 km from Kaludiya Pokuna Forest, 13 km from Sigiriya Lion Rock and 15 km fro'),
(155, 'The Elephant Corridor', 'Pothana,Sigiriya, Kimbissa', 'Puttalam', 'Elephant@gmail.com', '662286950', 'Elephant.lk', 7.94375, 80.7108, 'false', 'Set on 80 hectares of lush grounds, this serene, secluded resort is 4 km from the A6 highway and 8 k'),
(156, 'Camellia Resort and Spa', 'Audangawa, Kibissa, Sigiriya 21120', 'Kegalle', 'Camellia@yahoo.com', '662054103', 'Camellia.com', 7.99528, 80.737, 'false', 'Surrounded by lush vegetation, this relaxed hotel with an annexe is 8 km from Hurulu Eco park, 9 km'),
(157, 'Hotel Eden Garden', 'Hotel Eden Garden, Inamaluwa - Sigiriya Rd, Inamaluwa', 'Mannar', 'Garden@yahoo.com', '756800519', 'Garden.com', 7.9299, 80.6887, 'false', 'Amid tropical gardens off the A6 road, this laid-back hotel is 9 km from the ancient ruins of Sigiry'),
(158, 'Saunter paradise hotel', 'Ambepussa - Kurunegala - Trincomalee Hwy, Dambulla', 'Batticaloa', 'Saunter@gmail.com', '756865602', 'Saunter.com', 7.99284, 80.7253, 'false', 'Off the A6 road, and surrounded by lush greenery, this unpretentious hotel with cottages is 13 km fr'),
(159, 'Amaya Signature', 'Sun Shine Villa, Thalkotta Rd, Dambulla 21120', 'Batticaloa', 'Amaya@yahoo.com', '65665644', 'Amaya.lk', 7.89133, 80.6994, 'false', 'Beautiful atmosphere. 2 swimming pools were great. Rooms were very nice. Food is delicious in both t'),
(160, 'Amaara Forest Hotel', 'Indigaswewa, Sigiriya, Dambulla', 'Colombo', 'Amaara@yahoo.com', '56568855', 'Amaara.com', 8.00136, 80.7475, 'false', 'Amid tropical gardens off the A6 road, this laid-back hotel is 9 km from the ancient ruins of Sigiry'),
(161, 'Grand Kalundawa Waterfront Resort', 'Dambulla, Kalundawa Road, Dambuluoya Junction,', 'Colombo', 'Grand@yahoo.com', '727086000', 'Kalundawa .com', 7.80659, 80.659, 'false', 'Friendly and helpful staff, they gave great information for trustful tuk tuk drivers. Tasty welcome'),
(162, 'RHO Sigiriya Lake Edge Retreat', '143/B/3, Egodawewa Road, Galahitiyawa, Sigiriya', 'Puttalam', 'Sigiriya@yahoo.com', '56565656', 'Sigiriya.com', 7.93229, 80.7447, 'false', 'Very helpful staff, nice quiet place to relax after walking up Sigiriya. Excellent food, try the cur'),
(163, 'Wild Grass Nature Resort', 'Kumbukkadanwala Farmhouse Road Govigammanaya Main Road Kumbukkadanwala Sigiriya, Dambulla', 'Ratnapura', 'Wild@yahoo.com', '65656569', 'Wild.com', 7.90508, 80.7245, 'false', 'Warm and welcoming hospitality shown by a lovely team. Spent one night here at the start of our Sri'),
(164, 'Pelwehera Village Resort', 'Bulagala Junction, Habarana Road, Dambulla 21120', 'Nuwara Eliya', 'Pelwehera@yhoo.com', '56566656565', 'Pelwehera.com', 7.90391, 80.6694, 'false', 'We were very happy to spend 3 nights at this resort from 8-10 April.||The staff were all very pleasa'),
(165, 'Hotel Sigiriya', 'Hotel Road, Sigiriya, Sigiriya', 'Mannar', 'Sigiriya@yahoo.com', '56565646', 'Sigiriya.lk', 7.95044, 80.7631, 'false', 'Set on tropical gardens with views of the Lion Rock, this polished hotel is a 12-minute walk from th'),
(166, 'EKHO Sigiriya', 'Hotel Road, Sigiriya, Sigiriya', 'Colombo', 'EKHO@gmail.com', '65684462', 'EKHO.lk', 7.95209, 80.7552, 'false', 'Meals are served in a casual lounge, or in a reserved formal restaurant that has stone columns. A sh'),
(167, 'Gimanhala Hotel', 'Jaffna - Kandy Highway, 754 Anuradhapura Road, DambullaJaffna', 'Jaffna', 'Gimanhala@yahoo.com', '662286300', 'Gimanhala.com', 7.88025, 80.6507, 'false', 'Amid tropical gardens off the A6 road, this laid-back hotel is 9 km from the ancient ruins of Sigiry'),
(168, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sigiriya, an ancient city and fortress.The polished, warmly decorated rooms feature cable TV, free Wi-Fi and minifridges, along with tea and coffeemaking facilities. Upgraded rooms add butler service and verandas. Chic 2-bedroom suites include dining areas and whirlpool baths.The hotel has a bar, a teahouse and 2 restaurants, which offer organic dishes and open-air dining.'),
(169, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.'),
(170, 'Signature by Amaya', 'Sigiriya, Dambulla 21100', 'Badulla', 'Signature@outlook.com', '66446500', 'Amaya.com', 7.89156, 80.6996, 'false', 'Room service is available.Theres a colourful rooftop terrace with a pool and a bar serving light bites. Other perks include a simple eatery, a terrace with lake views, and an airy lounge, plus a fitness centre. Breakfast is offered for a fee.'),
(171, 'Surfing Wombats Hostel', 'Midigama A2, Ahangama 80860', 'Colombo', 'Surfing@gmail.com', '412254766', 'Surfing.lk', 5.96648, 80.3918, 'false', 'Chic hostel offering airy dorms &amp; private rooms, plus outdoor showers &amp; a restaurant.'),
(172, 'Ocean Bay Surf Resort', 'A2, Weligama 81700', 'Gampaha', 'Ocean@yahoo.com', '776206233', 'Ocean.com', 5.97461, 80.4383, 'false', 'Peaceful place with friendly staff. Lovely place for couples for weekend getaway. Payments will not be accepted via booking websites. So they should be done after arrival. Staff is exceptionally friendly and helpful'),
(173, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sigiriya, an ancient city and fortress.The polished, warmly decorated rooms feature cable TV, free Wi-Fi and minifridges, along with tea and coffeemaking facilities. Upgraded rooms add butler service and verandas. Chic 2-bedroom suites include dining areas and whirlpool baths.The hotel has a bar, a teahouse and 2 restaurants, which offer organic dishes and open-air dining.'),
(174, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.'),
(175, 'Signature by Amaya', 'Sigiriya, Dambulla 21100', 'Badulla', 'Signature@outlook.com', '66446500', 'Amaya.com', 7.89156, 80.6996, 'false', 'Room service is available.Theres a colourful rooftop terrace with a pool and a bar serving light bites. Other perks include a simple eatery, a terrace with lake views, and an airy lounge, plus a fitness centre. Breakfast is offered for a fee.'),
(176, 'Surfing Wombats Hostel', 'Midigama A2, Ahangama 80860', 'Colombo', 'Surfing@gmail.com', '412254766', 'Surfing.lk', 5.96648, 80.3918, 'false', 'Chic hostel offering airy dorms &amp; private rooms, plus outdoor showers &amp; a restaurant.'),
(177, 'Ocean Bay Surf Resort', 'A2, Weligama 81700', 'Gampaha', 'Ocean@yahoo.com', '776206233', 'Ocean.com', 5.97461, 80.4383, 'false', 'Peaceful place with friendly staff. Lovely place for couples for weekend getaway. Payments will not be accepted via booking websites. So they should be done after arrival. Staff is exceptionally friendly and helpful'),
(178, 'Ulagalla by Uga Escapes', 'Ulagalla Walawwa, Thirippane Ulagalla Road  50072 LK', 'Batticaloa', 'Ulagalla@gamil.com', '112328832', 'Ulagalla.com', 8.2061, 80.545, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.'),
(179, 'Jetwing Vil Uyana', 'Sigiriya, 21120', 'Kilinochchi', 'Uyana@ymail.com', '662286000', 'Uyana.lk', 7.93086, 80.7208, 'false', 'On sprawling grounds with reed beds, paddy fields and a lake, this imaginative, eco-chic hotel is 15 minutes walk from the Sigiriya Museum and 2 km from Sigiriya Lion Rock Fortress.Rustic wood cabins with thatched roofs provide complimentary Wi-Fi, flat-screen TVs and minibars, plus tea and coffeemaking facilities. Some add private plunge pools and/or furnished balconies.Breakfast (fee) is served in an upscale restaurant that has a terrace with views of the lake. There are also 2 bars. The spa offers a plunge pool, a steam room and Ayurvedic treatments. Other amenities include yoga classes, a gym and bike rentals.'),
(180, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sigiriya, an ancient city and fortress.The polished, warmly decorated rooms feature cable TV, free Wi-Fi and minifridges, along with tea and coffeemaking facilities. Upgraded rooms add butler service and verandas. Chic 2-bedroom suites include dining areas and whirlpool baths.The hotel has a bar, a teahouse and 2 restaurants, which offer organic dishes and open-air dining.'),
(181, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.'),
(182, 'Signature by Amaya', 'Sigiriya, Dambulla 21100', 'Badulla', 'Signature@outlook.com', '66446500', 'Amaya.com', 7.89156, 80.6996, 'false', 'Room service is available.Theres a colourful rooftop terrace with a pool and a bar serving light bites. Other perks include a simple eatery, a terrace with lake views, and an airy lounge, plus a fitness centre. Breakfast is offered for a fee.'),
(183, 'Surfing Wombats Hostel', 'Midigama A2, Ahangama 80860', 'Colombo', 'Surfing@gmail.com', '412254766', 'Surfing.lk', 5.96648, 80.3918, 'false', 'Chic hostel offering airy dorms &amp; private rooms, plus outdoor showers &amp; a restaurant.'),
(184, 'Ocean Bay Surf Resort', 'A2, Weligama 81700', 'Gampaha', 'Ocean@yahoo.com', '776206233', 'Ocean.com', 5.97461, 80.4383, 'false', 'Peaceful place with friendly staff. Lovely place for couples for weekend getaway. Payments will not be accepted via booking websites. So they should be done after arrival. Staff is exceptionally friendly and helpful'),
(185, 'Ulagalla by Uga Escapes', 'Ulagalla Walawwa, Thirippane Ulagalla Road  50072 LK', 'Batticaloa', 'Ulagalla@gamil.com', '112328832', 'Ulagalla.com', 8.2061, 80.545, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.'),
(186, 'Jetwing Vil Uyana', 'Sigiriya, 21120', 'Kilinochchi', 'Uyana@ymail.com', '662286000', 'Uyana.lk', 7.93086, 80.7208, 'false', 'On sprawling grounds with reed beds, paddy fields and a lake, this imaginative, eco-chic hotel is 15 minutes walk from the Sigiriya Museum and 2 km from Sigiriya Lion Rock Fortress.Rustic wood cabins with thatched roofs provide complimentary Wi-Fi, flat-screen TVs and minibars, plus tea and coffeemaking facilities. Some add private plunge pools and/or furnished balconies.Breakfast (fee) is served in an upscale restaurant that has a terrace with views of the lake. There are also 2 bars. The spa offers a plunge pool, a steam room and Ayurvedic treatments. Other amenities include yoga classes, a gym and bike rentals.'),
(187, 'Sigiriana Resort by Thilanka', '51 Godawalaya Morragollawa, Dambulla 21100', 'Kurunegala', 'Thilanka@yahoo.com', '664468001', 'Thilanka.lk', 7.82193, 80.6574, 'false', 'Surrounded by woodland, this unfussy hotel is an 8-minute walk from Dambulla river and 4 km from the Dambulla Cave Temple.Nestled amid greenery, the airy villas come with satellite TV, DVD players, safes and minibars, as well as tea and coffeemaking facilities, balconies and private pools.There are 2 eateries, 1 serving fusion cuisine, plus a poolside cafe and a chic bar. Other amenities include an outdoor pool, tennis, volleyball, archery and horseback riding, as well as a spa with yoga and steam baths.'),
(188, 'Fresco Water Villa', 'Fresco Water Villa Pvt Ltd, 72/A 4TH Mile Post, Sigiriya', 'Galle', 'Fresco@yahoo.com', '662286161', 'Fresco.com', 7.94573, 80.7355, 'false', 'Amid lush, sprawling gardens, this upscale hotel is 3 km from the ancient Sigiriya Lion Rock fortress and 6 km from the A6 highway.Set around a central garden with lily ponds, the airy, relaxed rooms feature balconies and satellite TV, plus minibars, and tea and coffeemaking facilities.Parking is available. Dining options include a restaurant with open-air seating, plus a bar. Thereâ€™s also an outdoor pool with a sundeck. Breakfast is extra.'),
(189, 'Aliya Resort &amp; Spa', 'Audangawa, Sigiriya 21120', 'Polonnaruwa', 'Aliya@gamil.com', '662040400', 'Aliya.lk', 7.99939, 80.7362, 'false', 'Set across a streamlined complex in the lush countryside, this refined resort is less than 1 km from the A6 motorway and 14 km from the ancient ruins of Sigiriya.Relaxed rooms with a modern vibe provide free Wi-Fi, flat-screens and sitting areas, plus minibars, and tea and coffeemaking facilities some add wooden baths and/or bedrooms on 2nd levels. Chic tents on wood platforms feature verandahs; suites offer kitchenettes and whirlpool tubs, along with private pools and saunas.Amenities include 3 polished restaurants, a cafe/bar, and an outdoor infinity pool with Sigiriya views. Theres also an Ayurvedic spa, a gym and a nightclub.'),
(190, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sigiriya, an ancient city and fortress.The polished, warmly decorated rooms feature cable TV, free Wi-Fi and minifridges, along with tea and coffeemaking facilities. Upgraded rooms add butler service and verandas. Chic 2-bedroom suites include dining areas and whirlpool baths.The hotel has a bar, a teahouse and 2 restaurants, which offer organic dishes and open-air dining.'),
(191, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.'),
(192, 'Signature by Amaya', 'Sigiriya, Dambulla 21100', 'Badulla', 'Signature@outlook.com', '66446500', 'Amaya.com', 7.89156, 80.6996, 'false', 'Room service is available.Theres a colourful rooftop terrace with a pool and a bar serving light bites. Other perks include a simple eatery, a terrace with lake views, and an airy lounge, plus a fitness centre. Breakfast is offered for a fee.'),
(193, 'Surfing Wombats Hostel', 'Midigama A2, Ahangama 80860', 'Colombo', 'Surfing@gmail.com', '412254766', 'Surfing.lk', 5.96648, 80.3918, 'false', 'Chic hostel offering airy dorms &amp; private rooms, plus outdoor showers &amp; a restaurant.'),
(194, 'Ocean Bay Surf Resort', 'A2, Weligama 81700', 'Gampaha', 'Ocean@yahoo.com', '776206233', 'Ocean.com', 5.97461, 80.4383, 'false', 'Peaceful place with friendly staff. Lovely place for couples for weekend getaway. Payments will not be accepted via booking websites. So they should be done after arrival. Staff is exceptionally friendly and helpful'),
(195, 'Ulagalla by Uga Escapes', 'Ulagalla Walawwa, Thirippane Ulagalla Road  50072 LK', 'Batticaloa', 'Ulagalla@gamil.com', '112328832', 'Ulagalla.com', 8.2061, 80.545, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.'),
(196, 'Jetwing Vil Uyana', 'Sigiriya, 21120', 'Kilinochchi', 'Uyana@ymail.com', '662286000', 'Uyana.lk', 7.93086, 80.7208, 'false', 'On sprawling grounds with reed beds, paddy fields and a lake, this imaginative, eco-chic hotel is 15 minutes walk from the Sigiriya Museum and 2 km from Sigiriya Lion Rock Fortress.Rustic wood cabins with thatched roofs provide complimentary Wi-Fi, flat-screen TVs and minibars, plus tea and coffeemaking facilities. Some add private plunge pools and/or furnished balconies.Breakfast (fee) is served in an upscale restaurant that has a terrace with views of the lake. There are also 2 bars. The spa offers a plunge pool, a steam room and Ayurvedic treatments. Other amenities include yoga classes, a gym and bike rentals.'),
(197, 'Sigiriana Resort by Thilanka', '51 Godawalaya Morragollawa, Dambulla 21100', 'Kurunegala', 'Thilanka@yahoo.com', '664468001', 'Thilanka.lk', 7.82193, 80.6574, 'false', 'Surrounded by woodland, this unfussy hotel is an 8-minute walk from Dambulla river and 4 km from the Dambulla Cave Temple.Nestled amid greenery, the airy villas come with satellite TV, DVD players, safes and minibars, as well as tea and coffeemaking facilities, balconies and private pools.There are 2 eateries, 1 serving fusion cuisine, plus a poolside cafe and a chic bar. Other amenities include an outdoor pool, tennis, volleyball, archery and horseback riding, as well as a spa with yoga and steam baths.'),
(198, 'Fresco Water Villa', 'Fresco Water Villa Pvt Ltd, 72/A 4TH Mile Post, Sigiriya', 'Galle', 'Fresco@yahoo.com', '662286161', 'Fresco.com', 7.94573, 80.7355, 'false', 'Amid lush, sprawling gardens, this upscale hotel is 3 km from the ancient Sigiriya Lion Rock fortress and 6 km from the A6 highway.Set around a central garden with lily ponds, the airy, relaxed rooms feature balconies and satellite TV, plus minibars, and tea and coffeemaking facilities.Parking is available. Dining options include a restaurant with open-air seating, plus a bar. Thereâ€™s also an outdoor pool with a sundeck. Breakfast is extra.'),
(199, 'Aliya Resort &amp; Spa', 'Audangawa, Sigiriya 21120', 'Polonnaruwa', 'Aliya@gamil.com', '662040400', 'Aliya.lk', 7.99939, 80.7362, 'false', 'Set across a streamlined complex in the lush countryside, this refined resort is less than 1 km from the A6 motorway and 14 km from the ancient ruins of Sigiriya.Relaxed rooms with a modern vibe provide free Wi-Fi, flat-screens and sitting areas, plus minibars, and tea and coffeemaking facilities; some add wooden baths and/or bedrooms on 2nd levels. Chic tents on wood platforms feature verandahs; suites offer kitchenettes and whirlpool tubs, along with private pools and saunas.Amenities include 3 polished restaurants, a cafe/bar, and an outdoor infinity pool with Sigiriya views. Theres also an Ayurvedic spa, a gym and a nightclub.'),
(200, 'Heritance Kandalama', '11, Dambulla 21100', 'Ratnapura', 'Heritance@yahoo.com', '665555000', 'Heritance.com', 7.86953, 80.7068, 'false', 'Set amidst jungle on a mountainside overlooking the Sigiriya rock fortress, this eco-chic hotel is next to Kandalama Reservoir and 10 km from the Golden Temple of Dambulla.Warm, elegant rooms feature balconies and luxurious bathrooms with reservoir views. All also offer free Wi-Fi, flat-screens and air-conditioning, as well as minibars and tea and coffeemaking facilities. Suites add DVD players and Jacuzzis; some offer butler service.Hot breakfast is served in an airy restaurant with a terrace. Theres also refined fusion dining. Other amenities include a relaxed bar and a spa, in addition to a library, a kids play area and 3 outdoor pools.'),
(201, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sigiriya, an ancient city and fortress.The polished, warmly decorated rooms feature cable TV, free Wi-Fi and minifridges, along with tea and coffeemaking facilities. Upgraded rooms add butler service and verandas. Chic 2-bedroom suites include dining areas and whirlpool baths.The hotel has a bar, a teahouse and 2 restaurants, which offer organic dishes and open-air dining.'),
(202, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.'),
(203, 'Signature by Amaya', 'Sigiriya, Dambulla 21100', 'Badulla', 'Signature@outlook.com', '66446500', 'Amaya.com', 7.89156, 80.6996, 'false', 'Room service is available.Theres a colourful rooftop terrace with a pool and a bar serving light bites. Other perks include a simple eatery, a terrace with lake views, and an airy lounge, plus a fitness centre. Breakfast is offered for a fee.'),
(204, 'Surfing Wombats Hostel', 'Midigama A2, Ahangama 80860', 'Colombo', 'Surfing@gmail.com', '412254766', 'Surfing.lk', 5.96648, 80.3918, 'false', 'Chic hostel offering airy dorms &amp; private rooms, plus outdoor showers &amp; a restaurant.'),
(205, 'Ocean Bay Surf Resort', 'A2, Weligama 81700', 'Gampaha', 'Ocean@yahoo.com', '776206233', 'Ocean.com', 5.97461, 80.4383, 'false', 'Peaceful place with friendly staff. Lovely place for couples for weekend getaway. Payments will not be accepted via booking websites. So they should be done after arrival. Staff is exceptionally friendly and helpful'),
(206, 'Ulagalla by Uga Escapes', 'Ulagalla Walawwa, Thirippane Ulagalla Road  50072 LK', 'Batticaloa', 'Ulagalla@gamil.com', '112328832', 'Ulagalla.com', 8.2061, 80.545, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.'),
(207, 'Jetwing Vil Uyana', 'Sigiriya, 21120', 'Kilinochchi', 'Uyana@ymail.com', '662286000', 'Uyana.lk', 7.93086, 80.7208, 'false', 'On sprawling grounds with reed beds, paddy fields and a lake, this imaginative, eco-chic hotel is 15 minutes walk from the Sigiriya Museum and 2 km from Sigiriya Lion Rock Fortress.Rustic wood cabins with thatched roofs provide complimentary Wi-Fi, flat-screen TVs and minibars, plus tea and coffeemaking facilities. Some add private plunge pools and/or furnished balconies.Breakfast (fee) is served in an upscale restaurant that has a terrace with views of the lake. There are also 2 bars. The spa offers a plunge pool, a steam room and Ayurvedic treatments. Other amenities include yoga classes, a gym and bike rentals.'),
(208, 'Sigiriana Resort by Thilanka', '51 Godawalaya Morragollawa, Dambulla 21100', 'Kurunegala', 'Thilanka@yahoo.com', '664468001', 'Thilanka.lk', 7.82193, 80.6574, 'false', 'Surrounded by woodland, this unfussy hotel is an 8-minute walk from Dambulla river and 4 km from the Dambulla Cave Temple.Nestled amid greenery, the airy villas come with satellite TV, DVD players, safes and minibars, as well as tea and coffeemaking facilities, balconies and private pools.There are 2 eateries, 1 serving fusion cuisine, plus a poolside cafe and a chic bar. Other amenities include an outdoor pool, tennis, volleyball, archery and horseback riding, as well as a spa with yoga and steam baths.'),
(209, 'Fresco Water Villa', 'Fresco Water Villa Pvt Ltd, 72/A 4TH Mile Post, Sigiriya', 'Galle', 'Fresco@yahoo.com', '662286161', 'Fresco.com', 7.94573, 80.7355, 'false', 'Amid lush, sprawling gardens, this upscale hotel is 3 km from the ancient Sigiriya Lion Rock fortress and 6 km from the A6 highway.Set around a central garden with lily ponds, the airy, relaxed rooms feature balconies and satellite TV, plus minibars, and tea and coffeemaking facilities.Parking is available. Dining options include a restaurant with open-air seating, plus a bar. Thereâ€™s also an outdoor pool with a sundeck. Breakfast is extra.'),
(210, 'Aliya Resort &amp; Spa', 'Audangawa, Sigiriya 21120', 'Polonnaruwa', 'Aliya@gamil.com', '662040400', 'Aliya.lk', 7.99939, 80.7362, 'false', 'Set across a streamlined complex in the lush countryside, this refined resort is less than 1 km from the A6 motorway and 14 km from the ancient ruins of Sigiriya.Relaxed rooms with a modern vibe provide free Wi-Fi, flat-screens and sitting areas, plus minibars, and tea and coffeemaking facilities; some add wooden baths and/or bedrooms on 2nd levels. Chic tents on wood platforms feature verandahs; suites offer kitchenettes and whirlpool tubs, along with private pools and saunas.Amenities include 3 polished restaurants, a cafe/bar, and an outdoor infinity pool with Sigiriya views. Theres also an Ayurvedic spa, a gym and a nightclub.'),
(211, 'Heritance Kandalama', '11, Dambulla 21100', 'Ratnapura', 'Heritance@yahoo.com', '665555000', 'Heritance.com', 7.86953, 80.7068, 'false', 'Set amidst jungle on a mountainside overlooking the Sigiriya rock fortress, this eco-chic hotel is next to Kandalama Reservoir and 10 km from the Golden Temple of Dambulla.Warm, elegant rooms feature balconies and luxurious bathrooms with reservoir views. All also offer free Wi-Fi, flat-screens and air-conditioning, as well as minibars and tea and coffeemaking facilities. Suites add DVD players and Jacuzzis; some offer butler service.Hot breakfast is served in an airy restaurant with a terrace. Theres also refined fusion dining. Other amenities include a relaxed bar and a spa, in addition to a library, a kids play area and 3 outdoor pools.'),
(212, 'Cinnamon Lodge Habarana', '02 50150, Habarana Roundabout, Habarana', 'Hambantota', 'Cinnamon@gamil.co', '662270011', 'Cinnamon.com', 8.03435, 80.7488, 'false', 'Set amid tropical forest, this upscale hotel is 9 km from Minneriya National Park and 16 km from Sigiriya, an ancient city and fortress.The polished, warmly decorated rooms feature cable TV, free Wi-Fi and minifridges, along with tea and coffeemaking facilities. Upgraded rooms add butler service and verandas. Chic 2-bedroom suites include dining areas and whirlpool baths.The hotel has a bar, a teahouse and 2 restaurants, which offer organic dishes and open-air dining.'),
(213, 'OZO Kandy Sri Lanka', '31 Saranankara Rd, Kandy 20000', 'Kandy', 'OZO@yahoo.com', '812030700', 'OZO.com', 7.2884, 80.6427, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.'),
(214, 'Signature by Amaya', 'Sigiriya, Dambulla 21100', 'Badulla', 'Signature@outlook.com', '66446500', 'Amaya.com', 7.89156, 80.6996, 'false', 'Room service is available.Theres a colourful rooftop terrace with a pool and a bar serving light bites. Other perks include a simple eatery, a terrace with lake views, and an airy lounge, plus a fitness centre. Breakfast is offered for a fee.'),
(215, 'Surfing Wombats Hostel', 'Midigama A2, Ahangama 80860', 'Colombo', 'Surfing@gmail.com', '412254766', 'Surfing.lk', 5.96648, 80.3918, 'false', 'Chic hostel offering airy dorms &amp; private rooms, plus outdoor showers &amp; a restaurant.'),
(216, 'Ocean Bay Surf Resort', 'A2, Weligama 81700', 'Gampaha', 'Ocean@yahoo.com', '776206233', 'Ocean.com', 5.97461, 80.4383, 'false', 'Peaceful place with friendly staff. Lovely place for couples for weekend getaway. Payments will not be accepted via booking websites. So they should be done after arrival. Staff is exceptionally friendly and helpful'),
(217, 'Ulagalla by Uga Escapes', 'Ulagalla Walawwa, Thirippane Ulagalla Road  50072 LK', 'Batticaloa', 'Ulagalla@gamil.com', '112328832', 'Ulagalla.com', 8.2061, 80.545, 'false', 'Surrounded by lush mountains dotted with residences, this sophisticated hotel is less than 1 km from Kandy Lake and 2 km from Kandy Railway Station.Modern rooms, some with mountain views, have free Wi-Fi, flat-screens and sitting areas, as well as rainfall showers, minifridges, and tea and coffeemaking facilities. Upgraded rooms add balconies with lake views, while suites provide separate living areas.');
INSERT INTO `hotel_details` (`id`, `hotel_name`, `address`, `district`, `email`, `phone`, `website`, `lat`, `lng`, `gallery`, `description`) VALUES
(218, 'Jetwing Vil Uyana', 'Sigiriya, 21120', 'Kilinochchi', 'Uyana@ymail.com', '662286000', 'Uyana.lk', 7.93086, 80.7208, 'false', 'On sprawling grounds with reed beds, paddy fields and a lake, this imaginative, eco-chic hotel is 15 minutes walk from the Sigiriya Museum and 2 km from Sigiriya Lion Rock Fortress.Rustic wood cabins with thatched roofs provide complimentary Wi-Fi, flat-screen TVs and minibars, plus tea and coffeemaking facilities. Some add private plunge pools and/or furnished balconies.Breakfast (fee) is served in an upscale restaurant that has a terrace with views of the lake. There are also 2 bars. The spa offers a plunge pool, a steam room and Ayurvedic treatments. Other amenities include yoga classes, a gym and bike rentals.'),
(219, 'Sigiriana Resort by Thilanka', '51 Godawalaya Morragollawa, Dambulla 21100', 'Kurunegala', 'Thilanka@yahoo.com', '664468001', 'Thilanka.lk', 7.82193, 80.6574, 'false', 'Surrounded by woodland, this unfussy hotel is an 8-minute walk from Dambulla river and 4 km from the Dambulla Cave Temple.Nestled amid greenery, the airy villas come with satellite TV, DVD players, safes and minibars, as well as tea and coffeemaking facilities, balconies and private pools.There are 2 eateries, 1 serving fusion cuisine, plus a poolside cafe and a chic bar. Other amenities include an outdoor pool, tennis, volleyball, archery and horseback riding, as well as a spa with yoga and steam baths.'),
(220, 'Fresco Water Villa', 'Fresco Water Villa Pvt Ltd, 72/A 4TH Mile Post, Sigiriya', 'Galle', 'Fresco@yahoo.com', '662286161', 'Fresco.com', 7.94573, 80.7355, 'false', 'Amid lush, sprawling gardens, this upscale hotel is 3 km from the ancient Sigiriya Lion Rock fortress and 6 km from the A6 highway.Set around a central garden with lily ponds, the airy, relaxed rooms feature balconies and satellite TV, plus minibars, and tea and coffeemaking facilities.Parking is available. Dining options include a restaurant with open-air seating, plus a bar. Thereâ€™s also an outdoor pool with a sundeck. Breakfast is extra.'),
(221, 'Aliya Resort &amp; Spa', 'Audangawa, Sigiriya 21120', 'Polonnaruwa', 'Aliya@gamil.com', '662040400', 'Aliya.lk', 7.99939, 80.7362, 'false', 'Set across a streamlined complex in the lush countryside, this refined resort is less than 1 km from the A6 motorway and 14 km from the ancient ruins of Sigiriya.Relaxed rooms with a modern vibe provide free Wi-Fi, flat-screens and sitting areas, plus minibars, and tea and coffeemaking facilities; some add wooden baths and/or bedrooms on 2nd levels. Chic tents on wood platforms feature verandahs; suites offer kitchenettes and whirlpool tubs, along with private pools and saunas.Amenities include 3 polished restaurants, a cafe/bar, and an outdoor infinity pool with Sigiriya views. Theres also an Ayurvedic spa, a gym and a nightclub.'),
(222, 'Heritance Kandalama', '11, Dambulla 21100', 'Ratnapura', 'Heritance@yahoo.com', '665555000', 'Heritance.com', 7.86953, 80.7068, 'false', 'Set amidst jungle on a mountainside overlooking the Sigiriya rock fortress, this eco-chic hotel is next to Kandalama Reservoir and 10 km from the Golden Temple of Dambulla.Warm, elegant rooms feature balconies and luxurious bathrooms with reservoir views. All also offer free Wi-Fi, flat-screens and air-conditioning, as well as minibars and tea and coffeemaking facilities. Suites add DVD players and Jacuzzis; some offer butler service.Hot breakfast is served in an airy restaurant with a terrace. Theres also refined fusion dining. Other amenities include a relaxed bar and a spa, in addition to a library, a kids play area and 3 outdoor pools.'),
(223, 'Amaya Lake', 'Kap Ela, Kandalama, Dambulla 21100', 'Puttalam', 'Amaya@yahoo.com', '114767846', 'Amaya.lk', 7.89377, 80.7006, 'false', 'A nice hotel surrounded by greenery and by the Kandalama lake. Very salubrious and you can see many varieties of birds and butterflies there. The staff is friendly and helpful. Chalets are cozy and comfortable. We enjoyed our stay at Amaya Lake.'),
(224, 'Habarana Village by Cinnamon', 'Habarana', 'Colombo', 'Habarana@gamil.com', '662270047', 'Habarana.com', 8.03681, 80.7499, 'false', 'Set amid lush forest off the A6 highway, this relaxed, rural resort on Habarana Lake is 18 km from Sigiriya Lion Rock, the ruins of a 5th-century city.Warmly decorated rooms with wood accents offer patios, free Wi-Fi and cable TV, as well as minibars, and tea and coffeemaking facilities. Suites add lake views, 4-poster beds, living areas, and open-air bathrooms with soaking tubs.A casual buffet restaurant with a terrace serves international cuisine. Theres also a cafe, and a bar with garden views. Other amenities include a spa, a triangle-shaped outdoor pool, and a cricket pitch, as well as tennis, badminton and volleyball courts.'),
(225, 'Cassandra Culture Resort', 'Sigiriya, Avudangawa', 'Ratnapura', 'Cassandra@yahoo.com', '664933636', 'Cassandra.com', 7.99229, 80.7339, 'false', 'Wonderful hotel, the buffet is delicious and offers plenty of choice. Beautiful pool. The staff is superfriendly and they offer extra services (laundry, carrying baggage to your room...). We had an excellent stay at this beautiful hotel.'),
(226, 'Sigiriya Village Hotel', 'Hotel Rd, Sigiriya', 'Matale', 'Sigiriya@yahoo.com', '662286803', 'Sigiriya.lk', 7.9498, 80.7612, 'false', 'On 10 landscaped hectares, this scenic resort is less than 1 km from the ruined rock fortress at Sigiriya and 16 km from Habarana train station.Set in separate bungalows, the warm rooms feature furnished balconies and tropical decor, as well as flat-screen TVs, minifridges, and tea and coffeemaking equipment. Upgraded rooms add sitting areas. Room service is available.Dining options include an open-air restaurant and a bar. Thereâ€™s also an Ayurvedic spa, an outdoor pool, and a sprawling garden with walking paths. Bike rentals are available.'),
(227, 'Sundaras Resort &amp; Spa', '189 Kandy Rd, Dambulla 21100', 'Nuwara Eliya', 'Sundaras@yahoo.com', '727086000', 'Sundaras.lk', 7.84977, 80.6532, 'false', 'On wooded grounds off the Kandyâ€“Jaffna Highway, this relaxed hotel is 1 km from the Golden Temple of Dambulla, which is in a cave, and 34 km from Minneriya National Park.Featuring balconies or terraces with garden views, the unfussy rooms have minibars, free Wi-Fi, and tea and coffeemaking equipment. Room service is available.Breakfast and parking are complimentary. Other amenities include an informal restaurant, an outdoor pool and a poolside bar. Theres also an Ayurvedic spa.'),
(228, 'The Paradise Resort &amp; Spa', 'Kubukkadanwala, Dambulla 21100', 'Mullaitivu', 'Paradise@yahoo.com', '662286300', 'Paradise.lk', 7.89234, 80.7252, 'false', 'This relaxed resort is 3 km from Kaludiya Pokuna Forest, 13 km from Sigiriya Lion Rock and 15 km from Dambulla Cave Temple.Airy rooms with wood furnishings and parquet floors offer free Wi-Fi, satellite TVs and terraces, plus safes, minibars, and tea and coffeemakers. Upgraded rooms and suites have living areas and/or Jacuzzis. Room service is available.Amenities consist of an outdoor pool with a kids section, a gym and a game room. Theres also a garden, a gift shop, a lounge, and meeting and event space. Dining options include 3 restaurants (1 is a pizzeria) and 2 bars. A spa offers Thai and Ayurveda treatments. Breakfast is available.'),
(229, 'The Elephant Corridor', 'Pothana,Sigiriya, Kimbissa', 'Puttalam', 'Elephant@gmail.com', '662286950', 'Elephant.lk', 7.94375, 80.7108, 'false', 'Set on 80 hectares of lush grounds, this serene, secluded resort is 4 km from the A6 highway and 8 km from Sigiriya, a striking rock topped with the ruins of an ancient fortress.Featuring balconies or terraces, the airy suites have stone walls, satellite TV and minifridges, plus safes, and tea and coffeemakers. All come with living areas, art supplies, and private indoor or outdoor plunge pools. A 4-bedroom villa with butler service sleeps up to 12 guests. Room service is available.Parking is free. Meals are offered in-room or on terraces. Theres also a library/bar, a gym, and an outdoor pool with a poolside bar, plus a spa and bike rentals.'),
(230, 'Camellia Resort and Spa', 'Audangawa, Kibissa, Sigiriya 21120', 'Kegalle', 'Camellia@yahoo.com', '662054103', 'Camellia.com', 7.99528, 80.737, 'false', 'Surrounded by lush vegetation, this relaxed hotel with an annexe is 8 km from Hurulu Eco park, 9 km from Sigiriya palace and 11 km from exhibits at Sigiriya Museum.Unassuming rooms with tile floors have free Wi-Fi, flat-screen TVs and sitting areas, along with balconies or terraces. Suites add whirlpool tubs. Rooms in the annexe feature views of wildlife.A restaurant with a terrace serves regional and international cuisine. Additional amenities include an outdoor pool with sunloungers, and a spa offering massages, a steam bath and a sauna, as well as gardens with seating'),
(231, 'Hotel Eden Garden', 'Hotel Eden Garden, Inamaluwa - Sigiriya Rd, Inamaluwa', 'Mannar', 'Garden@yahoo.com', '756800519', 'Garden.com', 7.9299, 80.6887, 'false', 'Amid tropical gardens off the A6 road, this laid-back hotel is 9 km from the ancient ruins of Sigirya, and 11 km from the historic Golden Temple of Dambulla.The colourful, casual rooms feature TVs and balconies. Upgraded rooms add minibars, and tea and coffeemaking facilities. Room service is available 24/7.Amenities include an outdoor pool and a restaurant. Theres also event space for up to 300 people.'),
(232, 'Saunter paradise hotel', 'Ambepussa - Kurunegala - Trincomalee Hwy, Dambulla', 'Batticaloa', 'Saunter@gmail.com', '756865602', 'Saunter.com', 7.99284, 80.7253, 'true', 'Off the A6 road, and surrounded by lush greenery, this unpretentious hotel with cottages is 13 km from 5th-century ruins and a rock fortress at Sigiriya, and 29 km from scenic Ritigala Strict Natural Reserve.Relaxed cottages with garden views offer free Wi-Fi and cable TV, plus safes and minifridges. All have tea and coffeemaking equipment, and en suite bathrooms.Parking is complimentary. Other amenities include a restaurant with a terrace, and a bar, plus BBQ facilities and an outdoor pool'),
(233, 'Amaya Signature', 'Sun Shine Villa, Thalkotta Rd, Dambulla 21120', 'Batticaloa', 'Amaya@yahoo.com', '65665644', 'Amaya.lk', 7.89133, 80.6994, 'true', 'Beautiful atmosphere. 2 swimming pools were great. Rooms were very nice. Food is delicious in both the signature restaurant and the lake buffet. Staff is very friendly and helpful. The view of the Lake in the morning is superb. Would recommend to anyone.'),
(234, 'Amaara Forest Hotel', 'Indigaswewa, Sigiriya, Dambulla', 'Colombo', 'Amaara@yahoo.com', '56568855', 'Amaara.com', 8.00136, 80.7475, 'false', 'Amid tropical gardens off the A6 road, this laid-back hotel is 9 km from the ancient ruins of Sigirya, and 11 km from the historic Golden Temple of Dambulla.The colourful, casual rooms feature TVs and balconies. Upgraded rooms add minibars, and tea and coffeemaking facilities. Room service is available 24/7.Amenities include an outdoor pool and a restaurant. Theres also event space for up to 300 people.'),
(235, 'Grand Kalundawa Waterfront Resort', 'Dambulla, Kalundawa Road, Dambuluoya Junction,', 'Colombo', 'Grand@yahoo.com', '727086000', 'Kalundawa .com', 7.80659, 80.659, 'false', 'Friendly and helpful staff, they gave great information for trustful tuk tuk drivers. Tasty welcome fruit juices. Located perfectly to visit the Dambulla cave Tempel (10 minutes ride) and Sigiriya lion rock (40 minutes ride). The outside'),
(236, 'RHO Sigiriya Lake Edge Retreat', '143/B/3, Egodawewa Road, Galahitiyawa, Sigiriya', 'Puttalam', 'Sigiriya@yahoo.com', '56565656', 'Sigiriya.com', 7.93229, 80.7447, 'false', 'Very helpful staff, nice quiet place to relax after walking up Sigiriya. Excellent food, try the curry and rice for dinner, its amazing and only 700 rupee. Nice sunset over the lake. Also keep an eye out for the fireflies at night. Its a little far out so you will have to tuk tuk everywhere. The hotel doesnt have bikes to rent.'),
(237, 'Wild Grass Nature Resort', 'Kumbukkadanwala Farmhouse Road Govigammanaya Main Road Kumbukkadanwala Sigiriya, Dambulla', 'Ratnapura', 'Wild@yahoo.com', '65656569', 'Wild.com', 7.90508, 80.7245, 'false', 'Warm and welcoming hospitality shown by a lovely team. Spent one night here at the start of our Sri Lankan adventure. ||Highly recommend dinner @ the rock! The scenery is stunning and worth the small hike. A very unique experience, the food served is tasty. ||Comfortable, clean and unique stay! Very peaceful! ||||'),
(238, 'Pelwehera Village Resort', 'Bulagala Junction, Habarana Road, Dambulla 21120', 'Nuwara Eliya', 'Pelwehera@yhoo.com', '56566656565', 'Pelwehera.com', 7.90391, 80.6694, 'false', 'We were very happy to spend 3 nights at this resort from 8-10 April.||The staff were all very pleasant, helpful and engaging.|| The range of food was extensive, and suitable for our requirements.||We have been thinking of you all since the terrible events of Easter Sunday, and hope that peace and harmony return to your people'),
(239, 'Hotel Sigiriya', 'Hotel Road, Sigiriya, Sigiriya', 'Mannar', 'Sigiriya@yahoo.com', '56565646', 'Sigiriya.lk', 7.95044, 80.7631, 'false', 'Set on tropical gardens with views of the Lion Rock, this polished hotel is a 12-minute walk from the ancient Sigiriya palace and archaeological site, and 24 km from the scenic Kandalama Reservoir.The colourful rooms offer French doors leading to patios, plus sitting areas, flat-screen TVs and minibars. They also offer bottled water, and tea and coffeemaking facilities.Complimentary breakfast is served in the open-air restaurant, and theres a rustic, convivial bar. Other amenities include 2 outdoor pools and an Ayurvedic spa, as well as tennis courts, traditional live music and event space.'),
(240, 'EKHO Sigiriya', 'Hotel Road, Sigiriya, Sigiriya', 'Colombo', 'EKHO@gmail.com', '65684462', 'EKHO.lk', 7.95209, 80.7552, 'false', 'Meals are served in a casual lounge, or in a reserved formal restaurant that has stone columns. A shuttle to the nearest bus stop is available.Less than 1 km from the ruins of the storied city of Sigiriya, this cosy hotel is 19 km from Minneriya National Park and 8 km from the Lenawa Junction Bus Stop.Surrounding a grassy courtyard, the relaxed rooms feature free Wi-Fi, minifridges, and tea and coffeemaking equipment, in addition to safes. Exterior entrances lead to verandas with outdoor seating. All provide scenic views of Sigiriya rock.'),
(241, 'Gimanhala Hotel', 'Jaffna - Kandy Highway, 754 Anuradhapura Road, DambullaJaffna', 'Jaffna', 'Gimanhala@yahoo.com', '662286300', 'Gimanhala.com', 7.88025, 80.6507, 'false', 'Amid tropical gardens off the A6 road, this laid-back hotel is 9 km from the ancient ruins of Sigirya, and 11 km from the historic Golden Temple of Dambulla.The colourful, casual rooms feature TVs and balconies. Upgraded rooms add minibars, and tea and coffeemaking facilities. Room service is available 24/7.Amenities include an outdoor pool and a restaurant. Theres also event space for up to 300 people.');

-- --------------------------------------------------------

--
-- Table structure for table `user_account`
--

CREATE TABLE `user_account` (
  `id` int(11) NOT NULL,
  `username` varchar(120) NOT NULL,
  `password` varchar(120) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user_account`
--

INSERT INTO `user_account` (`id`, `username`, `password`) VALUES
(1, 'guna', 'kuna123');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `gallery`
--
ALTER TABLE `gallery`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `hotel_details`
--
ALTER TABLE `hotel_details`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user_account`
--
ALTER TABLE `user_account`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `gallery`
--
ALTER TABLE `gallery`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `hotel_details`
--
ALTER TABLE `hotel_details`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=242;

--
-- AUTO_INCREMENT for table `user_account`
--
ALTER TABLE `user_account`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
